// src/lib/positive-quotes.ts

export const positiveQuotes: string[] = [
  "The best way to predict the future is to create it.",
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Happiness is not something readymade. It comes from your own actions.",
  "It is during our darkest moments that we must focus to see the light.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
  "The power of imagination makes us infinite.",
  "If you want to lift yourself up, lift up someone else.",
  "The only true wisdom is in knowing you know nothing.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "The successful warrior is the average man, with laser-like focus.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "It is never too late to be what you might have been.",
  "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.",
  "What we achieve inwardly will change outer reality.",
  "Experience is a hard teacher because she gives the test first, the lesson afterward.",
  "To handle yourself, use your head; to handle others, use your heart.",
  "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "You can't use up creativity. The more you use, the more you have.",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
  "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
  "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
  "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
  "I find that the harder I work, the more luck I seem to have.",
  "The starting point of all achievement is desire.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "All progress takes place outside the comfort zone.",
  "You may be disappointed if you fail, but you are doomed if you don't try.",
  "Failure is another steppingstone to greatness.",
  "The mind is everything. What you think you become.",
  "The only place where success comes before work is in the dictionary.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
  "Don't let the fear of striking out keep you from playing the game.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It is our choices, Harry, that show what we truly are, far more than our abilities.",
  "The power of a man's mind is only limited by his own ability to imagine and to create.",
  "The journey of a thousand miles begins with a single step.",
  "We must be willing to let go of the life we have planned, so as to have the life that is waiting for us.",
  "Try not to become a man of success, but rather try to become a man of value.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The question isn't who is going to let me; it's who is going to stop me.",
  "When you cease to dream you cease to live.",
  "The best revenge is massive success."
];
